#!/bin/bash
# Script 5: Open Source Manifesto Generator
# Author: [Your Name] | Reg No: [Your Reg No]
# Course: Open Source Software | Capstone Project
# Purpose: Asks the user three questions interactively and generates
#          a personalised open-source philosophy statement saved to a .txt file.

# Alias concept demonstrated: in a real shell session you could define
# alias generate_manifesto='bash script5_manifesto_generator.sh'
# to run this script with a memorable shorthand command.

DATE=$(date '+%d %B %Y')
OUTPUT="manifesto_$(whoami).txt"

echo "========================================================"
echo "         Open Source Manifesto Generator                "
echo "========================================================"
echo ""
echo "  Answer three questions to generate your personal"
echo "  open-source philosophy statement."
echo ""
echo "--------------------------------------------------------"

read -p "  1. Name one open-source tool you use every day: " TOOL
echo ""

read -p "  2. In one word, what does 'freedom' mean to you in software? " FREEDOM
echo ""

read -p "  3. Name one thing you would build and share freely with the world: " BUILD
echo ""

if [ -z "$TOOL" ] || [ -z "$FREEDOM" ] || [ -z "$BUILD" ]; then
    echo "  Error: All three questions must be answered. Please re-run the script."
    exit 1
fi

echo "--------------------------------------------------------"
echo "  Generating your manifesto..."
echo ""

{
    echo "========================================================"
    echo "  OPEN SOURCE MANIFESTO"
    echo "  Generated by: $(whoami)"
    echo "  Date: $DATE"
    echo "========================================================"
    echo ""
    echo "  I believe in the power of open software."
    echo ""
    echo "  Every day, I rely on $TOOL — a tool built by people"
    echo "  who chose to share their work freely rather than lock it away."
    echo "  That choice made my work possible. It made this possible."
    echo ""
    echo "  To me, freedom in software means $FREEDOM."
    echo "  Not just the freedom to use a tool, but the freedom to"
    echo "  understand it, question it, improve it, and pass it on."
    echo "  That is what separates open source from a gift with conditions."
    echo ""
    echo "  If I could build one thing and share it with the world freely,"
    echo "  it would be $BUILD."
    echo "  I would share it because I have benefited from the work of"
    echo "  thousands of developers I will never meet. Sharing is not"
    echo "  generosity — it is participation in something larger than"
    echo "  any single person or company."
    echo ""
    echo "  The software that runs the world was not written by one person."
    echo "  It was written by communities that chose openness over control."
    echo "  I choose to be part of that."
    echo ""
    echo "  -- $(whoami) | $DATE"
    echo "========================================================"
} > "$OUTPUT"

echo "  Manifesto saved to: $OUTPUT"
echo ""
echo "========================================================"
echo "  YOUR MANIFESTO"
echo "========================================================"
echo ""
cat "$OUTPUT"
